# This is a basic workflow to help you get started with Actions

name: Publication Update Email

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths: 
    - 'bib/feamster.bib'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  email:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Must set: MAIL_USER, MAIL_PASS, UCHICAGO_COMM_EMAIL, EMAIL_TO, EMAIL_CC, EMAIL_FROM
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.cs.uchicago.edu
          server_port: 587
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: New Publication from Nick Feamster
          from: ${{ secrets.EMAIL_FROM }}
          to: ${{ secrets.EMAIL_TO}}
          cc: ${{ secrets.EMAIL_CC }}
          body: https://people.cs.uchicago.edu/~feamster/publications.html
